
#ifndef ENGINE_STRUCT_MACROS_H
#define ENGINE_STRUCT_MACROS_H

#define CARD_SUIT_MACRO(CARD) ( (CARD & CARD_SUIT_MASK) >> CARD_SUIT_SHIFT)
#define CARD_VALUE_MACRO(CARD) ( (CARD & CARD_VALUE_MASK) >> CARD_VALUE_SHIFT)

#define SUIT_CARD_MACRO(SUIT) ( (SUIT << CARD_SUIT_SHIFT) & CARD_SUIT_MASK)
#define VALUE_CARD_MACRO(VALUE) ( (VALUE << CARD_VALUE_SHIFT) & CARD_VALUE_MASK)

#define ALLOC_CARD_SUIT(CARD, SUIT) ( (CARD & ~CARD_SUIT_MASK) | (SUIT & CARD_SUIT_MASK) )
#define ALLOC_CARD_VALUE(CARD, VALUE) ( (CARD & ~CARD_VALUE_MASK) | (VALUE & CARD_VALUE_MASK) )

#endif
