
#ifndef ENGINE_STRUCT_MACROS_H
#define ENGINE_STRUCT_MACROS_H

#define CARD_SUIT_MACRO(CARD) ( (CARD & CARD_SUIT_MASK) >> CARD_SUIT_SHIFT)
#define CARD_RANK_MACRO(CARD) ( (CARD & CARD_RANK_MASK) >> CARD_RANK_SHIFT)

#define SUIT_CARD_MACRO(SUIT) ( (SUIT << CARD_SUIT_SHIFT) & CARD_SUIT_MASK)
#define RANK_CARD_MACRO(RANK) ( (RANK << CARD_RANK_SHIFT) & CARD_RANK_MASK)

#define ALLOC_CARD_SUIT(CARD, SUIT) ( (CARD & ~CARD_SUIT_MASK) | (SUIT & CARD_SUIT_MASK) )
#define ALLOC_CARD_RANK(CARD, RANK) ( (CARD & ~CARD_RANK_MASK) | (RANK & CARD_RANK_MASK) )

#define SUIT_RANK_CARD(SUIT, RANK) ( SUIT_CARD_MACRO(SUIT) | RANK_CARD_MACRO(RANK) )

#define TURN_CARD_SHOW(CARD) (CARD | CARD_SHOW_MASK)
#define TURN_CARD_DOWN(CARD) (CARD & ~CARD_SHOW_MASK)
#define CARD_SIDE_SHOW(CARD) (CARD & CARD_SHOW_MASK)

#endif
